[package]
    edition="2021"
    name   ="advent_of_code_template"
    version="0.1.0"

    # See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
    priority-queue="1.3.1"

[profile.release]
    lto=true
